version: '3.7'

services:
  go-app:
    container_name: guest_security
    image: go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=guard password=123456 dbname=guard_db sslmode=disable"
    ports:
      - "8001:8001"
    depends_on:
      - go_db

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: guard
      POSTGRES_DB: guard_db
    ports:
      - "5433:5432"   # Use default PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}
